// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: boards.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const adjustBoardPositions = `-- name: AdjustBoardPositions :one
UPDATE boards SET state_positions = $1 WHERE id = $2 RETURNING id, name, created_at, updated_at, description, state_positions
`

type AdjustBoardPositionsParams struct {
	StatePositions []uuid.UUID
	ID             uuid.UUID
}

func (q *Queries) AdjustBoardPositions(ctx context.Context, arg AdjustBoardPositionsParams) (Board, error) {
	row := q.db.QueryRowContext(ctx, adjustBoardPositions, pq.Array(arg.StatePositions), arg.ID)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		pq.Array(&i.StatePositions),
	)
	return i, err
}

const createBoard = `-- name: CreateBoard :one
INSERT INTO boards (id, name, description, created_at, updated_at)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    NOw(),
    NOW()
)
RETURNING id, name, created_at, updated_at, description, state_positions
`

type CreateBoardParams struct {
	Name        string
	Description sql.NullString
}

func (q *Queries) CreateBoard(ctx context.Context, arg CreateBoardParams) (Board, error) {
	row := q.db.QueryRowContext(ctx, createBoard, arg.Name, arg.Description)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		pq.Array(&i.StatePositions),
	)
	return i, err
}

const deleteBoard = `-- name: DeleteBoard :one
DELETE FROM boards WHERE id = $1 RETURNING id, name, created_at, updated_at, description, state_positions
`

func (q *Queries) DeleteBoard(ctx context.Context, id uuid.UUID) (Board, error) {
	row := q.db.QueryRowContext(ctx, deleteBoard, id)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		pq.Array(&i.StatePositions),
	)
	return i, err
}

const getAllBoards = `-- name: GetAllBoards :many
SELECT id, name, created_at, updated_at, description, state_positions FROM boards ORDER BY created_at DESC
`

func (q *Queries) GetAllBoards(ctx context.Context) ([]Board, error) {
	rows, err := q.db.QueryContext(ctx, getAllBoards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Board
	for rows.Next() {
		var i Board
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Description,
			pq.Array(&i.StatePositions),
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBoardByID = `-- name: GetBoardByID :one
SELECT id, name, created_at, updated_at, description, state_positions FROM boards WHERE id = $1
`

func (q *Queries) GetBoardByID(ctx context.Context, id uuid.UUID) (Board, error) {
	row := q.db.QueryRowContext(ctx, getBoardByID, id)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		pq.Array(&i.StatePositions),
	)
	return i, err
}

const truncateBoards = `-- name: TruncateBoards :exec
TRUNCATE TABLE boards CASCADE
`

func (q *Queries) TruncateBoards(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, truncateBoards)
	return err
}

const updateBoard = `-- name: UpdateBoard :one
UPDATE boards SET name = $1 WHERE id = $2 RETURNING id, name, created_at, updated_at, description, state_positions
`

type UpdateBoardParams struct {
	Name string
	ID   uuid.UUID
}

func (q *Queries) UpdateBoard(ctx context.Context, arg UpdateBoardParams) (Board, error) {
	row := q.db.QueryRowContext(ctx, updateBoard, arg.Name, arg.ID)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Description,
		pq.Array(&i.StatePositions),
	)
	return i, err
}
