// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: boards.sql

package database

import (
	"context"
)

const createBoard = `-- name: CreateBoard :one
INSERT INTO boards (id, name, created_at, updated_at)
VALUES (
    gen_random_uuid(),
    $1,
    NOw(),
    NOW()
)
RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateBoard(ctx context.Context, name string) (Board, error) {
	row := q.db.QueryRowContext(ctx, createBoard, name)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
