// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: boards.sql

package database

import (
	"context"
)

const createBoard = `-- name: CreateBoard :one
INSERT INTO boards (id, name, created_at, updated_at)
VALUES (
    gen_random_uuid(),
    $1,
    NOw(),
    NOW()
)
RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateBoard(ctx context.Context, name string) (Board, error) {
	row := q.db.QueryRowContext(ctx, createBoard, name)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllBoards = `-- name: GetAllBoards :many
SELECT id, name, created_at, updated_at FROM boards ORDER BY created_at DESC
`

func (q *Queries) GetAllBoards(ctx context.Context) ([]Board, error) {
	rows, err := q.db.QueryContext(ctx, getAllBoards)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Board
	for rows.Next() {
		var i Board
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
