// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: columns.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createColumn = `-- name: CreateColumn :one
INSERT INTO columns (id, title, created_at, updated_at, board_id, position)
VALUES (
    gen_random_uuid(),
    $1,
    NOW(),
    NOW(),
    $2,
    $3
) RETURNING id, title, description, created_at, updated_at, board_id, position
`

type CreateColumnParams struct {
	Title    string
	BoardID  uuid.UUID
	Position int32
}

func (q *Queries) CreateColumn(ctx context.Context, arg CreateColumnParams) (Column, error) {
	row := q.db.QueryRowContext(ctx, createColumn, arg.Title, arg.BoardID, arg.Position)
	var i Column
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BoardID,
		&i.Position,
	)
	return i, err
}

const deleteColumn = `-- name: DeleteColumn :exec

DELETE FROM columns WHERE id = $1
`

func (q *Queries) DeleteColumn(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteColumn, id)
	return err
}

const getColumns = `-- name: GetColumns :many
SELECT id, title, description, created_at, updated_at, board_id, position from columns WHERE board_id = $1 ORDER BY position ASC
`

func (q *Queries) GetColumns(ctx context.Context, boardID uuid.UUID) ([]Column, error) {
	rows, err := q.db.QueryContext(ctx, getColumns, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Column
	for rows.Next() {
		var i Column
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BoardID,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateColumnPosition = `-- name: UpdateColumnPosition :exec
UPDATE columns SET position = $2 WHERE id = $1
`

type UpdateColumnPositionParams struct {
	ID       uuid.UUID
	Position int32
}

func (q *Queries) UpdateColumnPosition(ctx context.Context, arg UpdateColumnPositionParams) error {
	_, err := q.db.ExecContext(ctx, updateColumnPosition, arg.ID, arg.Position)
	return err
}
