// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identities.sql

package database

import (
	"context"
)

const createIdentity = `-- name: CreateIdentity :one
INSERT INTO identities (id, password_hash, email, created_at, updated_at)
VALUES(gen_random_uuid(), $1, $2, NOW(), NOW()) RETURNING id, email, password_hash, created_at, updated_at
`

type CreateIdentityParams struct {
	PasswordHash string
	Email        string
}

func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) (Identity, error) {
	row := q.db.QueryRowContext(ctx, createIdentity, arg.PasswordHash, arg.Email)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIdentityByEmail = `-- name: GetIdentityByEmail :one
SELECT id, email, password_hash, created_at, updated_at FROM identities WHERE email = $1
`

func (q *Queries) GetIdentityByEmail(ctx context.Context, email string) (Identity, error) {
	row := q.db.QueryRowContext(ctx, getIdentityByEmail, email)
	var i Identity
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
