// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Board struct {
	ID          uuid.UUID
	Name        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Description sql.NullString
	CreatorID   uuid.UUID
}

type Column struct {
	ID          uuid.UUID
	Title       string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
	BoardID     uuid.UUID
	Position    int32
}

type Identity struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type Task struct {
	ID          uuid.UUID
	BoardID     uuid.UUID
	ColumnID    uuid.UUID
	Title       string
	Description sql.NullString
	Position    int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	ID        uuid.UUID
	Email     string
	FirstName string
	LastName  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
