// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Board struct {
	ID             uuid.UUID
	Name           string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Description    sql.NullString
	StatePositions []uuid.UUID
}

type State struct {
	ID          uuid.UUID
	Title       string
	Description sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
	BoardID     uuid.UUID
}
