// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: states.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createState = `-- name: CreateState :one
INSERT INTO states (id, title, created_at, updated_at, board_id)
VALUES (
    gen_random_uuid(),
    $1,
    NOW(),
    NOW(),
    $2
) RETURNING id, title, description, created_at, updated_at, board_id
`

type CreateStateParams struct {
	Title   string
	BoardID uuid.UUID
}

func (q *Queries) CreateState(ctx context.Context, arg CreateStateParams) (State, error) {
	row := q.db.QueryRowContext(ctx, createState, arg.Title, arg.BoardID)
	var i State
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BoardID,
	)
	return i, err
}

const deleteState = `-- name: DeleteState :exec
DELETE FROM states WHERE id = $1
`

func (q *Queries) DeleteState(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteState, id)
	return err
}

const getStates = `-- name: GetStates :many
SELECT id, title, description, created_at, updated_at, board_id from states WHERE board_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetStates(ctx context.Context, boardID uuid.UUID) ([]State, error) {
	rows, err := q.db.QueryContext(ctx, getStates, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []State
	for rows.Next() {
		var i State
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BoardID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
