// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: states.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createState = `-- name: CreateState :one
INSERT INTO states (id, title, created_at, updated_at, board_id)
VALUES (
    gen_random_uuid(),
    $1,
    NOW(),
    NOW(),
    $2
) RETURNING id, title, description, created_at, updated_at, board_id
`

type CreateStateParams struct {
	Title   string
	BoardID uuid.UUID
}

func (q *Queries) CreateState(ctx context.Context, arg CreateStateParams) (State, error) {
	row := q.db.QueryRowContext(ctx, createState, arg.Title, arg.BoardID)
	var i State
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BoardID,
	)
	return i, err
}
