// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (id, board_id, column_id, title, description, position, created_at, updated_at)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4,
    $5,
    NOW(),
    NOW()
) 
RETURNING id, board_id, column_id, title, description, position, created_at, updated_at
`

type CreateTaskParams struct {
	BoardID     uuid.UUID
	ColumnID    uuid.UUID
	Title       string
	Description sql.NullString
	Position    int32
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.BoardID,
		arg.ColumnID,
		arg.Title,
		arg.Description,
		arg.Position,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.ColumnID,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTask, id)
	return err
}

const getColumnTasks = `-- name: GetColumnTasks :many
SELECT id, board_id, column_id, title, description, position, created_at, updated_at FROM tasks WHERE column_id = $1 ORDER BY position ASC
`

func (q *Queries) GetColumnTasks(ctx context.Context, columnID uuid.UUID) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getColumnTasks, columnID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.ColumnID,
			&i.Title,
			&i.Description,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getColumnTasksForUpdate = `-- name: GetColumnTasksForUpdate :many
SELECT id, board_id, column_id, title, description, position, created_at, updated_at FROM tasks WHERE column_id = $1 ORDER BY position ASC FOR UPDATE
`

func (q *Queries) GetColumnTasksForUpdate(ctx context.Context, columnID uuid.UUID) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getColumnTasksForUpdate, columnID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.ColumnID,
			&i.Title,
			&i.Description,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTask = `-- name: GetTask :one
SELECT id, board_id, column_id, title, description, position, created_at, updated_at FROM tasks WHERE id = $1
`

func (q *Queries) GetTask(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.ColumnID,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskForShare = `-- name: GetTaskForShare :one
SELECT id, board_id, column_id, title, description, position, created_at, updated_at FROM tasks WHERE id = $1 FOR SHARE
`

func (q *Queries) GetTaskForShare(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskForShare, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.ColumnID,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const shiftTasksAfter = `-- name: ShiftTasksAfter :exec
UPDATE tasks
SET position = position + $2
WHERE position > $3 AND column_id = $1
`

type ShiftTasksAfterParams struct {
	ColumnID uuid.UUID
	Delta    int32
	After    int32
}

func (q *Queries) ShiftTasksAfter(ctx context.Context, arg ShiftTasksAfterParams) error {
	_, err := q.db.ExecContext(ctx, shiftTasksAfter, arg.ColumnID, arg.Delta, arg.After)
	return err
}

const shiftTasksBetween = `-- name: ShiftTasksBetween :exec
UPDATE tasks
SET position = position + $2
WHERE position > $3 AND position < $4 AND column_id = $1
`

type ShiftTasksBetweenParams struct {
	ColumnID uuid.UUID
	Delta    int32
	After    int32
	Before   int32
}

func (q *Queries) ShiftTasksBetween(ctx context.Context, arg ShiftTasksBetweenParams) error {
	_, err := q.db.ExecContext(ctx, shiftTasksBetween,
		arg.ColumnID,
		arg.Delta,
		arg.After,
		arg.Before,
	)
	return err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET
    column_id = COALESCE($2, column_id),
    title = COALESCE($3, title),
    description = COALESCE($4, description),
    position = COALESCE($5, position),
    updated_at = NOW()
where id = $1
RETURNING id, board_id, column_id, title, description, position, created_at, updated_at
`

type UpdateTaskParams struct {
	ID          uuid.UUID
	ColumnID    uuid.NullUUID
	Title       sql.NullString
	Description sql.NullString
	Position    sql.NullInt32
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTask,
		arg.ID,
		arg.ColumnID,
		arg.Title,
		arg.Description,
		arg.Position,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.ColumnID,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTaskPosition = `-- name: UpdateTaskPosition :exec
UPDATE tasks SET position = $2 WHERE id = $1
`

type UpdateTaskPositionParams struct {
	ID       uuid.UUID
	Position int32
}

func (q *Queries) UpdateTaskPosition(ctx context.Context, arg UpdateTaskPositionParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskPosition, arg.ID, arg.Position)
	return err
}
