// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (id, board_id, column_id, title, description, position, created_at, updated_at)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4,
    $5,
    NOW(),
    NOW()
) 
RETURNING id, board_id, column_id, title, description, position, created_at, updated_at
`

type CreateTaskParams struct {
	BoardID     uuid.UUID
	ColumnID    uuid.UUID
	Title       string
	Description sql.NullString
	Position    int32
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.BoardID,
		arg.ColumnID,
		arg.Title,
		arg.Description,
		arg.Position,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.ColumnID,
		&i.Title,
		&i.Description,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getColumnTasks = `-- name: GetColumnTasks :many
SELECT id, board_id, column_id, title, description, position, created_at, updated_at FROM tasks WHERE column_id = $1 AND board_id = $2
`

type GetColumnTasksParams struct {
	ColumnID uuid.UUID
	BoardID  uuid.UUID
}

func (q *Queries) GetColumnTasks(ctx context.Context, arg GetColumnTasksParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getColumnTasks, arg.ColumnID, arg.BoardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.ColumnID,
			&i.Title,
			&i.Description,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskPosition = `-- name: UpdateTaskPosition :exec
UPDATE tasks SET position = $2 WHERE id = $1
`

type UpdateTaskPositionParams struct {
	ID       uuid.UUID
	Position int32
}

func (q *Queries) UpdateTaskPosition(ctx context.Context, arg UpdateTaskPositionParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskPosition, arg.ID, arg.Position)
	return err
}
