services:
  api:
    image: zifkage/kanban-api
    container_name: kanban-api
    environment:
      API_PORT: 8080
      DB_URL: postgres://testuser:testpassword@postgres_db:5432/kanban-db?sslmode=disable
      JWT_SECRET: Jw3XDepNwBl3WRe1k0XDI65X/iLdsV/dAOmGyM/jRaftF/wEifBHQFGLYQEcMJhCchUQyBwReSk8zZNTt3goMA==
    ports:
      - "8080:8080"
  postgres_db:
    image: postgres:16-alpine
    container_name: go_postgres_db
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: kanban-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d kanban-db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
