name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      DB_URL: ${{ secrets.DB_URL }}

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.27.0"

      - name: Install goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Install sqlc
        uses: sqlc-dev/setup-sqlc@v4
        with:
          sqlc-version: "1.31.1"

      - name: Generate database package
        run: sqlc generate

      - name: Run DB migrations
        run: ./scripts/migrateup.sh

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: "Set up Google Cloud SDK"
        uses: google-github-actions/setup-gcloud@v3

      - name: Build
        run: ./scripts/buildprod.sh

      - name: Deploy to Cloud Run
        run: gcloud builds submit --tag us-central1-docker.pkg.dev/kanban-api-507318/kanban-app-ar-repo/kanban-api:latest . && gcloud run deploy kanban-api --image us-central1-docker.pkg.dev/kanban-api-507318/kanban-app-ar-repo/kanban-api:latest --region us-central1 --allow-unauthenticated --project kanban-api-507318 --max-instances=4
